export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const LOGIN_DATA_REQUEST = 'LOGIN_DATA_REQUEST';
export const LOGIN_DATA_SUCCESS = 'LOGIN_DATA_SUCCESS';
export const LOGIN_DATA_FAILURE = 'LOGIN_DATA_FAILURE';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const ADVERTS_LOADED_REQUEST = 'ADVERTS_LOADED_REQUEST';
export const ADVERTS_LOADED_SUCCESS = 'ADVERTS_LOADED_SUCCESS';
export const ADVERTS_LOADED_FAILURE = 'ADVERTS_LOADED_FAILURE';

export const DETAILS_LOADED_REQUEST = 'DETAILS_LOADED_REQUEST';
export const DETAILS_LOADED_SUCCESS = 'DETAILS_LOADED_SUCCESS';
export const DETAILS_LOADED_FAILURE = 'DETAILS_LOADED_FAILURE';

export const ADVERT_CREATED_REQUEST = 'ADVERT_CREATED_REQUEST';
export const ADVERT_CREATED_SUCCESS = 'ADVERT_CREATED_SUCCESS';
export const ADVERT_CREATED_FAILURE = 'ADVERT_CREATED_FAILURE';

export const ADVERT_DELETE_REQUEST = 'ADVERT_DELETE_REQUEST';
export const ADVERT_DELETE_SUCCESS = 'ADVERT_DELETE_SUCCESS';
export const ADVERT_DELETE_FAILURE = 'ADVERT_DELETE_FAILURE';

export const TAGS_LOAD_REQUEST = 'TAGS_LOAD_REQUEST';
export const TAGS_LOAD_SUCCESS = 'TAGS_LOAD_SUCCESS';
export const TAGS_LOAD_FAILURE = 'TAGS_LOAD_FAILURE';

export const UI_RESET_ERROR = 'UI_RESET_ERROR'